// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD63pkEymOXhbf0bJI0nLUsB2jo3gh2l70',
    appId: '1:342268067759:web:c7b77b1f16df897e45395a',
    messagingSenderId: '342268067759',
    projectId: 'dllm-ed8c6',
    authDomain: 'dllm-ed8c6.firebaseapp.com',
    storageBucket: 'dllm-ed8c6.appspot.com',
    measurementId: 'G-JT06PNJHW8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzG8qdBwBUCWoxkm0jsXFav393ImGGV5w',
    appId: '1:342268067759:android:e32a1248a8f66fc045395a',
    messagingSenderId: '342268067759',
    projectId: 'dllm-ed8c6',
    storageBucket: 'dllm-ed8c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6NNCFPVk65d6cp_cxzKOAYZSveK35JO4',
    appId: '1:342268067759:ios:c682c313b2647ef645395a',
    messagingSenderId: '342268067759',
    projectId: 'dllm-ed8c6',
    storageBucket: 'dllm-ed8c6.appspot.com',
    iosClientId: '342268067759-ioj8pq4939tiird8104ntf817i076996.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6NNCFPVk65d6cp_cxzKOAYZSveK35JO4',
    appId: '1:342268067759:ios:854bd5a0ecebae2545395a',
    messagingSenderId: '342268067759',
    projectId: 'dllm-ed8c6',
    storageBucket: 'dllm-ed8c6.appspot.com',
    iosClientId: '342268067759-k289e4ippvsbomnppb320hbsiehqmcdf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2.RunnerTests',
  );
}
